package evidencia.pkg3.bd.CustomLists.Departamentos;

/**
 *
 * @author Ricardo
 */
public class DepartamentoListItem extends javax.swing.JPanel {

    /**
     * Creates new form DepartementoListItemn
     */
    public DepartamentoListItem() {
        initComponents();
    }
    
    public void setItem(Object obj) {
        if (obj instanceof Departamento) {
            Departamento item = (Departamento) obj;
            deptLabel.setText(item.getDepartamento());
        } else {
            deptLabel.setText(obj + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deptLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        deptLabel.setBackground(new java.awt.Color(255, 255, 255));
        deptLabel.setFont(new java.awt.Font("Space Grotesk Light", 0, 18)); // NOI18N
        deptLabel.setForeground(new java.awt.Color(0, 0, 0));
        deptLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/department.png"))); // NOI18N
        deptLabel.setText("Departamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(deptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deptLabel;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
