package evidencia.pkg3.bd.CustomLists.Carreras;

/**
 *
 * @author Ricardo
 */
public class CarreraListItem extends javax.swing.JPanel {

    /**
     * Creates new form CarreraListItem
     */
    public CarreraListItem() {
        initComponents();
    }
    
    public void setItem(Object obj) {
        if (obj instanceof Carrera) {
            Carrera item = (Carrera) obj;
            careerLabel.setText(item.getCarrera());
            descLabel.setText(item.getDescripcion());
            deptLabel.setText(item.getDepartamento());
        } else {
            careerLabel.setText(obj + "");
            descLabel.setText(obj + "");
            deptLabel.setText(obj + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        careerLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        careerLabel.setFont(new java.awt.Font("Space Grotesk Light", 0, 14)); // NOI18N
        careerLabel.setForeground(new java.awt.Color(0, 0, 0));
        careerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/career.png"))); // NOI18N
        careerLabel.setText("Carrera");

        descLabel.setFont(new java.awt.Font("Space Grotesk Light", 0, 14)); // NOI18N
        descLabel.setForeground(new java.awt.Color(0, 0, 0));
        descLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/descripcion.png"))); // NOI18N
        descLabel.setText("Descripcion");

        deptLabel.setFont(new java.awt.Font("Space Grotesk Light", 0, 14)); // NOI18N
        deptLabel.setForeground(new java.awt.Color(0, 0, 0));
        deptLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/department.png"))); // NOI18N
        deptLabel.setText("Departamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(careerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deptLabel)))
                .addContainerGap())
            .addComponent(separator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(careerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel)
                    .addComponent(deptLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel careerLabel;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
