package evidencia.pkg3.bd.CustomLists.Alumnos;

/**
 *
 * @author Ricardo
 */
public class AlumnosListItem extends javax.swing.JPanel {

    /**
     * Creates new form AlumnosListItem
     */
    public AlumnosListItem() {
        initComponents();
    }

    public void setItem(Object obj) {
        if (obj instanceof Alumno) {
            Alumno item = (Alumno) obj;
            studentName.setText(item.getNombre());
            studentCareer.setText(item.getCarrera());
            studentStatus.setText(item.getEstatus());
        } else {
            studentName.setText(obj + "");
            studentCareer.setText(obj + "");
            studentStatus.setText(obj + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        studentName = new javax.swing.JLabel();
        studentCareer = new javax.swing.JLabel();
        studentStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        studentName.setFont(new java.awt.Font("Space Grotesk Light", 0, 14)); // NOI18N
        studentName.setForeground(new java.awt.Color(0, 0, 0));
        studentName.setText("Nombre, apellidos");

        studentCareer.setFont(new java.awt.Font("Space Grotesk Light", 0, 14)); // NOI18N
        studentCareer.setForeground(new java.awt.Color(0, 0, 0));
        studentCareer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/career.png"))); // NOI18N
        studentCareer.setText("Carrera");

        studentStatus.setFont(new java.awt.Font("Space Grotesk Light", 0, 14)); // NOI18N
        studentStatus.setForeground(new java.awt.Color(0, 0, 0));
        studentStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/status.png"))); // NOI18N
        studentStatus.setText("No Inscrito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentCareer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(studentStatus)))
                .addContainerGap())
            .addComponent(separator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentCareer)
                    .addComponent(studentStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel studentCareer;
    private javax.swing.JLabel studentName;
    private javax.swing.JLabel studentStatus;
    // End of variables declaration//GEN-END:variables
}
